### ISSUE TITLE
GPIO port state stuck

### ISSUE THREAD

**Issue by VladNord** [jdeneef/ha_gpiod#14]
Hello.
The question is a little off topic, but still help me figure it out.
I have a conditional doorbell, which is a normally open button (without backlighting), which is connected to a raspberry with two wires (gpio12 and gnd), no pull-up or pull-down resistors. Cable length approx 10m.
Everything worked and then last night the bell went off by itself and now it has a status of constantly on.
Button is fine, it continues to work as should, but looks like something is wrong with the raspberry.

The strange thing is that a year ago I had a similar problem, but with other ports that also stuck in their state. 
I "solved" it by changing ports.

What am I doing wrong?

Thanks for help.

Here is code which i use with integration: 

```
    gpiod:
      path: '/dev/gpiochip0'

    binary_sensor:
    
      - platform: gpiod
        sensors:
        - name: "doorbell_button"
          port: 12
          debounce: 50
          active_low: true
```
